print(True and True)
print(False and True)
print(1 == 1 and 2 == 1)
print("test" == "test")
print(1 == 1 or 2 != 1)
print(True and 1  == 1)
print(False and 0 != 0)
print(True or 1 == 1)
print("test" == "testing")
print(1 != 0 and 2 == 1)
print("test" != "testing")
print("not (10 == 1 or 1000 == 1000)")
print(not ("testing" == "testing" and "Zed" == "Cool Guy"))
print(1 == 1 and (not ("testing" == 1 or 1 == 0)))
print(3 == 3 and (not ("testing" == "testing" or "Python" == "Fun")))